<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$title = $block->escapeHtml($block->getMethod()->getTitle());
?>
<dl class="payment-method">
    <h1>PIX TEST USER</h1>
    <dt class="title"><?= /* @noEscape */ $title ?></dt>
    <?php if ($specificInfo) : ?>
        <dd class="content">
            <table class="data table">
                <caption class="table-caption"><?= /* @noEscape */ $title ?></caption>
                <?php foreach ($specificInfo as $label => $value) : ?>
                    <?php
                        if ($label === 'QR Code do Pix' || $label === 'Pix QR Code') :
                            continue;
                        endif;
                    ?>
                    <tr>
                        <th scope="row"><?= $block->escapeHtml($label) ?></th>
                        <td>
                            <?php if ($label === 'qrcode_url') : ?>
                                <img src="<?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>" width="276" style="" />
                            <?php else : ?>
                                <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
        </dd>
    <?php endif;?>
</dl>
<?= $block->getChildHtml() ?>
