<?php
/**
 * @var MercadoPago\Core\Block\CustomPix\Success $block
 */
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();
$paymentResponse = $payment->getAdditionalInformation("paymentResponse");
$payment_method = $this->getPaymentMethod();
$pixImg = $this->getPixImg();
$expirationInfo = $this->getConfigExpirationInfo();
$link_to_order = '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>';
?>

<?php if ($payment_method == 'mercadopago_custom_pix') : ?>

<div id="box-mercadopago">

            <p class="mp-details-title">
            <?php echo __('Order %1 received! Now you just need to pay with Pix to finalize your purchase', $link_to_order); ?>
            </p>

            <div class="mp-details-pix">

            <div class="mp-col-md-4">

                <img src="<?php echo $pixImg; ?> " class="mp-details-pix-img" />

                <p class="mp-details-pix-title">
                    <?php echo __('How to pay with Pix:'); ?>
                </p>
                <ul class="mp-steps-congrats mp-pix-left">
                    <li class="mp-details-list">
                        <p class="mp-details-pix-number-p">1</p>
                        <p class="mp-details-list-description"><?php echo __('Go to your bank\'s app or website'); ?></p>
                    </li>
                    <li class="mp-details-list">
                        <p class="mp-details-pix-number-p">
                            2
                        </p>
                        <p class="mp-details-list-description"><?php echo __('Search for the option to pay with Pix'); ?></p>
                    </li>
                    <li class="mp-details-list">
                        <p class="mp-details-pix-number-p">
                            3
                        </p>
                        <p class="mp-details-list-description"><?php echo __('Scan the QR code or Pix code'); ?></p>
                    </li>
                    <li class="mp-details-list">
                        <p class="mp-details-pix-number-p">
                            4
                        </p>
                        <p class="mp-details-list-description"><?php echo __('Done! You will see the payment confirmation'); ?></p>
                    </li>
                </ul>

            </div>

            <div class="content-box">
                <div class="content-box__row">
                    <div id="banck-transfer-html">
                        <div class="text-container mp-mb-16">
                            <h2 class="heading-2 os-step__title">Quase lá! Pague via Pix para concluir sua compra</h2>
                        </div>
                        <div class="mp-flex mp-stretch-item">
                            <div class="mp-flex-item-round-border mp-ta-center mp-bg-light-grey mp-padding-24 mp-mr-8">
                                <div class="mp-flex-item-column mp-fc-black mp-ta-center">
                                    <div class="mp-lh-120 mp-mp-fw-normal mp-fs-16 mp-fc-black mp-mobile-fs-14">Valor:</div>
                                        <div id=pix-amount class="mp-lh-120 mp-fw-600 mp-fs-24 mp-fc-black mp-mobile-fs-16">R$&nbsp;<?php echo number_format($paymentResponse['transaction_amount'], 2, ',', '.'); ?></div>
                                    </div>
                                </div>
                            <div class="mp-flex-item-round-border mp-ta-center mp-bg-light-grey mp-padding-24">
                                <div class="mp-flex-item-column mp-fc-black mp-ta-center">
                                    <div class="mp-lh-120 mp-mp-fw-normal mp-fs-16 mp-fc-black mp-mobile-fs-14">Vencimento:</div>
                                    <div id=pix-due-date class="mp-lh-120 mp-fw-600 mp-fs-24 mp-fc-black mp-mobile-fs-16"><?php echo __($expirationInfo); ?></div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="text-container">
                                <div class="mp-flex mp-mb-16">
                                    <h3 class="heading-3">Escaneie este código QR para pagar</h3>
                                    <div class="mp-tooltip mp-img-fix-width">
                                        <img src="https://http2.mlstatic.com/static/org-img/mkt/email-mkt-assets/op-plugins/shopify/important.png" width="15.6px" height="15.6px" alt="Important" style="margin-left: 8.2px; margin-top: 16.0px">
                                        <span class="mp-tooltiptext">
                                            Antes de confirmar a compra, você verá o valor a pagar e as informações do vendedor.
                                        </span>
                                    </div>
                                </div>
                                <p class="mp-mt-0">1. Acesse o seu banco ou aplicativo de pagamentos</p>
                                <p class="mp-mt-0">2. Escolha pagar via Pix com código QR</p>
                                <p class="mp-mt-0">3. Escaneie o seguinte código</p>
                            </div>
                            <div>
                                <?php if (isset($paymentResponse['point_of_interaction']) && $paymentResponse['point_of_interaction']['transaction_data']['qr_code_base64']) { ?>
                                <img class="mp-img-center mp-details-pix-qr-img" src="data:image/jpeg;base64,<?php echo $paymentResponse['point_of_interaction']['transaction_data']['qr_code_base64']; ?>" />
                                <?php } ?>
                            </div>
                            <hr class="mp-bottom-line mp-mt-24 mp-mb-24">
                        </div>
                        <div>
                            <div class="text-container">
                                <h3 class="heading-3 mp-mb-16">Ou pague com o código Pix Copia e Cola</h3>
                                <p>Acesse o seu banco ou aplicativo de pagamentos e escolha pagar via Pix. Em seguida, cole o seguinte código de pagamento:</p>
                            </div>
                            <div class="mp-mt-16 mp-mb-16">
                                <span class="mp-ta-center">
                                    <input id="mp-qr-code" value="<?php echo $paymentResponse['point_of_interaction']['transaction_data']['qr_code']; ?>" class="mp-qr-input"></input>
                                </span>
                                <span class="mp-fade-out-gradient"></span>
                            </div>
                            <div class="mp-flex mp-stretch-item">
                                <button onclick="copy_qr_code()" class="mp-details-pix-button" onclick="true"><?php echo __('Copy code'); ?></button>
                                    <script>
                                        function copy_qr_code() {
                                            var copyText = document.getElementById("mp-qr-code");
                                            copyText.select();
                                            copyText.setSelectionRange(0, 99999)
                                            document.execCommand("copy");
                                        }
                                    </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </div>
</div>

    <div id="logo-mercadopago">
        <img src="<?php echo $block->getLogoMP();?>">
    </div>

    <div class="primary button-success">
        <a class="action primary continue"
        href="<?php echo $block->escapeUrl($block->getUrl()) ?>"><span><?php /* @escapeNotVerified */
                echo __('Continue Shopping') ?></span></a>
    </div>

<?php endif; ?>
