<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \MercadoPago\Core\Block\Adminhtml\System\Config\Button $block
 * @see \MercadoPago\Core\Block\Adminhtml\System\Config\Button
 */
?>
<div class="installment_button">
    <button onclick="javascript:window.open('<?= $block->escapeUrl(MercadoPago\Core\Helper\Country::changeUrlByCountry($block->getButtonUrl())) ?>'); return false;"
            class="scalable" type="button" id="<?= /* @noEscape */ $block->getHtmlId() ?>">
        <span><span><span><?= $block->escapeHtml($block->getButtonLabel()) ?></span></span></span>
    </button>
</div>