<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>

<?php if ($specificInfo) : ?>
    <h1>Pix Test! Admin</h1>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value) : ?>
            <?php
                if ($label === 'qrcode_url') :
                    continue;
                endif;
            ?>
            <tr>
                <th><?= $block->escapeHtml($label) ?>:</th>
                <td>
                    <?php if ($label === 'QR Code do Pix' || $label === 'Pix QR Code') : ?>
                        <img src="data:image/jpg;base64,<?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>" width="276" style="" />
                    <?php else : ?>
                        <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
