<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
        <?php foreach ($specificInfo as $label => $value): ?>
            <?php
            if ($label === 'QR Code'):
                continue;
                endif;
            ?>
            <tr>
                <th><?= $block->escapeHtml(__($label)) ?>:</th>
                <td style="word-break: break-word;">
                    <?php if ($label === 'Pix QR Code'): ?>
                        <img src="data:image/jpg;base64,<?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>" width="207" style="" />
                    <?php else: ?>
                        <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray(__($value), true)))) ?>
                    <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
