<?php
/**
 * @var MercadoPago\Core\Block\Basic\Failure $block
 */

$checkoutUrl = $block->escapeUrl($block->getCheckoutUrl());
?>

<div id="box-mercadopago">
    <h2 class="mercadopago-title">
        <?= /* @escapeNotVerified */ __('It was unable to complete payment with Mercado Pago!'); ?>
    </h2>

    <p><?= /* @escapeNotVerified */ __('Click on the button below to try the payment again:') ?></p>
</div>

<div class="primary button-success">
    <a
        class="action primary continue"
        href="<?= $checkoutUrl ?>"
    >
        <span>
            <?php /* @escapeNotVerified */ echo __('Retry payment') ?>
        </span>
    </a>
</div>

<div id="logo-mercadopago" style="margin-top: 40px">
    <img src="<?php echo $block->getLogoMP();?>">
</div>
