<?php
/**
 * @var MercadoPago\Core\Block\CustomBankTransfer\Success $block
 */
$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();
$paymentResponse = $payment->getAdditionalInformation("paymentResponse");
$payment_method = $this->getPaymentMethod();

//generate link to order
$successMsg = 'Your order %1 has been successfully generated.';
$link_to_order = '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>';
?>


<?php
if ($this->checkExistCallback() == false && $this->getRedirectUserStatus()) {
    ?>
    <script>
        window.location.href = "<?php echo $paymentResponse['transaction_details']['external_resource_url']; ?>";
    </script>
<?php } ?>


<div id="box-mercadopago">

    <?php if ($payment_method == 'mercadopago_custom_bank_transfer') { ?>

        <?php if ($this->checkExistCallback() == false) { ?>

            <h2 class="mercadopago-title">
                <?php /* @escapeNotVerified */
                echo __('Thank you for your purchase!'); ?>
            </h2>

            <p>
                <?php /* @escapeNotVerified */
                echo __(
                    'Your order %1 has been successfully generated.',
                    '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>'
                );
                ?>
            </p>

            <p>
                <?php /* @escapeNotVerified */
                echo __('The payment will be credited in less than 1 hour.'); ?>
            </p>

            <?php if (isset($paymentResponse['transaction_details']) && $paymentResponse['transaction_details']['external_resource_url']) { ?>

                <a href="<?php echo $block->escapeUrl(urldecode($paymentResponse['transaction_details']['external_resource_url'])); ?>"
                   id="btn-boleto-mercadopago">
                    <?php /* @escapeNotVerified */
                    echo __('Pay'); ?>
                </a>

            <?php } ?>

        <?php } else { ?>


            <?php
            $message_status = $this->getMessageByStatus($paymentResponse);
            if (isset($message_status['title']) && isset($message_status['message'])) {
                ?>
                <h2 class="mercadopago-title"><?php echo $block->escapeHtml($message_status['title']); ?></h2>

                <p><?php echo $block->escapeHtml($message_status['message']); ?></p>

            <?php } else { ?>
                <p><?php /* @escapeNotVerified */
                    echo __($successMsg, $link_to_order); ?></p>
            <?php } ?>

            <?php if ($paymentResponse['status'] != 'rejected' && (isset($message_status['title']) && isset($message_status['message']))): ?>
                <p><?php /* @escapeNotVerified */
                    echo __($successMsg, $link_to_order); ?></p>
            <?php endif; ?>

            <h3 class="mercadopago-title-info-payment"><?php /* @escapeNotVerified */
                echo __('Payment information'); ?></h3>

            <?php if (isset($paymentResponse['id'])) { ?>
                <p><?php echo __('Payment id (Mercado Pago): %1', $paymentResponse['id']); ?></p>
            <?php } ?>

            <?php if (isset($paymentResponse['payment_method_id'])) { ?>
                <p><?php echo __('Payment Method: %1', ucfirst($paymentResponse['payment_method_id'])); ?></p>
            <?php } ?>

            <?php if (isset($paymentResponse['status'])) { ?>
                <p><?php echo __('Payment Status: %1', ucfirst($paymentResponse['status'])); ?></p>
            <?php } ?>

            <?php if (isset($paymentResponse['id'])) { ?>
                <p><?php echo __('Payment Status Detail: %1', ucfirst($paymentResponse['status_detail'])); ?></p>
            <?php } ?>


        <?php } ?>

    <?php } else {
        echo __('Error getting the link to the ticket. Please contact the seller.');
    } ?>


</div>

<div id="logo-mercadopago">
    <img src="<?php echo $block->getLogoMP();?>">
</div>

<div class="primary button-success">
    <?php if (!empty($paymentResponse) && $paymentResponse['status'] == 'rejected'): ?>
        <a class="action primary continue" href="<?php echo $block->escapeUrl($block->getCheckoutUrl()) ?>">
            <span><?php /* @escapeNotVerified */ echo __('Retry payment') ?></span>
        </a>
    <?php else: ?>
        <a class="action primary continue" href="<?php echo $block->escapeUrl($block->getUrl()) ?>">
            <span><?php /* @escapeNotVerified */ echo __('Continue Shopping') ?></span>
        </a>
    <?php endif; ?>
</div>
