<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$specificInfo = $block->getSpecificInformation();
$paymentTitle = $block->getMethod()->getConfigData('title', $block->getInfo()->getOrder()->getStoreId());
?>
<?= $block->escapeHtml($paymentTitle) ?>

<?php if ($specificInfo): ?>
    <table class="data-table admin__table-secondary">
    <?php foreach ($specificInfo as $label => $value): ?>
        <tr>
            <th><?= $block->escapeHtml(__($label)) ?>:</th>
            <td>
                <?php if ($label === 'Link'): ?>
                    <a href="<?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray($value, true)))) ?>" target="_blank" >
                        <?= __('Generate Ticket') ?>
                    </a>
                <?php else: ?>
                    <?= /* @noEscape */ nl2br($block->escapeHtml(implode("\n", $block->getValueAsArray(__($value), true)))) ?>
                <?php endif; ?>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
<?php endif;?>

<?= $block->getChildHtml() ?>
