<?php
    /**
     * @var MercadoPago\Core\Block\CustomWebpay\Failure $block
     */

   $checkoutUrl = $block->escapeUrl($block->getCheckoutUrl());
?>

<div id="box-mercadopago">
    <h2 class="mercadopago-title">
        <?= /* @escapeNotVerified */ __('It was unable to complete payment with Webpay!'); ?>
    </h2>

    <p><?= /* @escapeNotVerified */ __('Click on the button below to try the payment again:') ?></p>
</div>

<div class="primary button-success">
    <a
        class="action primary continue"
        href="<?= $checkoutUrl ?>"
    >
        <span>
            <?php /* @escapeNotVerified */ echo __('Retry payment') ?>
        </span>
    </a>
</div>

<div id="logo-mercadopago" style="margin-top: 40px">
    <img src="https://secure.mlstatic.com/components/resources/mp/desktop/css/assets/desktop-logo-mercadopago.png"/>
</div>
