<?php

/**
 * @var MercadoPago\Core\Block\CustomTicket\Success $block
 */

$order = $this->getOrder();
$total = $this->getTotal();
$payment = $this->getPayment();
$paymentResponse = $payment->getAdditionalInformation("paymentResponse");
$payment_method = $this->getPaymentMethod();
?>

<?php if ($payment_method == 'mercadopago_customticket') : ?>

    <div id="box-mercadopago">
        <?php if ($payment_method == 'mercadopago_customticket') { ?>
            <h2 class="mercadopago-title"><?php /* @escapeNotVerified */
                echo __('Thank you for your purchase!'); ?></h2>
            <p>
                <?php /* @escapeNotVerified */
                echo __(
                    'Your order %1 has been successfully generated.',
                    '<a href="' . $block->escapeUrl($this->getOrderUrl()) . '">' . $block->escapeHtml($order->getIncrementId()) . '</a>'
                );
                ?>
            </p>
            <p>
                <?php echo __('Generate the ticket and pay it wherever you want.'); ?>
            </p>
            <p>
                <?php if (isset($paymentResponse['payment_method_id']) && $paymentResponse['payment_method_id'] == 'bolbradesco') {
                    /* @escapeNotVerified */
                    echo __('Will be approved within 2 business days.');
                }?>
            </p>

            <?php if (isset($paymentResponse['transaction_details']) && $paymentResponse['transaction_details']['external_resource_url']) { ?>

                <a href="<?php echo $block->escapeUrl(urldecode($paymentResponse['transaction_details']['external_resource_url'])); ?>" target="_blank" id="btn-boleto-mercadopago">
                    <?php /* @escapeNotVerified */
                    echo __('Generate Ticket'); ?>
                </a>
            <?php } else {
                echo __('Error getting the link to the ticket. Please contact the seller.');
            } ?>
        <?php } ?>

    </div>

    <div id="logo-mercadopago">
        <img src="<?php echo $block->getLogoMP(); ?>">
    </div>

    <div class="primary button-success">
        <a class="action primary continue" href="<?php echo $block->escapeUrl($block->getUrl()) ?>"><span><?php /* @escapeNotVerified */
                                                                                                            echo __('Continue Shopping') ?></span></a>
    </div>

<?php endif; ?>
